name: Test Website
on:
  pull_request:
    branches: ["*"]

jobs:
  publish:
    name: Test Website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    
      - name: Check out ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node ğŸ“¦
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache directory path ğŸª„
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies ğŸ§ª
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Change directory
        run: cd docs

      - name: Install dependencies ğŸ“¦
        run: yarn install

      - name: Lint ğŸ”
        run: yarn run lint

      - name: Build site ğŸ”¨
        run: yarn run build
